### ISSUE TITLE
can i duplicate the code

### ISSUE THREAD

**Issue by SimonCropp** [lars-erik/approvaltests.imageapproval#2]
I was wondering if you would mind if i duplicated your code to create a [comparer for Verify](https://github.com/VerifyTests/Verify/blob/master/docs/comparer.md). obviously i would give a prominent callout to you in the readme. Or alternatively, I can help you create the comparer, and you can own the project + code

**Comment by lars-erik** [comment]
Would be super happy to hand it over. Maybe I could just PR this to you in some way?

My use case for it is kind of shelved for now due to it running for too long as is. and we've got too frequent changes for it to help. Have high hopes for it to be useful in a more stable situation soon.  
Until then I won't have any time to focus on it, so as said happy to hand it over.

**Comment by SimonCropp** [comment]
> shelved for now due to it running for too long as is

so the algorithm takes too long to run?

**Comment by lars-erik** [comment]
@SimonCropp It depends on how big the images are and how many diffs you want to produce. But there are definite optimization possibilities by using other APIs in ImageSharp as well.

In the use-case I have there's a webpage measuring 1920 x 4140 that takes 1 minute to compare / generate 2 diffs for.  
A 400 x 4927 mobile version takes 15 seconds.  

So not too bad. I think I've over reacted to some CI runs that took an hour because of an outdated chrome driver. 🤦‍♂️

There _are_ still optimization possibilities, though.

**Comment by SimonCropp** [comment]
have u considered shrinking the images prior to doing the diff?
